services:
  mi-base-datos:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=admin_user_aquamovil-virginia
    ports:
      - "3306:3306"
    volumes:
    - ./db_data:/var/lib/mysql
    restart: always

  mi-app-java:
    build: ./aquanovil-back-virginia
    container_name: spring_boot_app
    ports:
      - "8086:8086"
    depends_on:
      - mi-base-datos
    environment:
      # Aquí está el truco: usamos el nombre del servicio 'mi-base-datos'
      - SPRING_DATASOURCE_URL=jdbc:mysql://mi-base-datos:3306/admin_user_aquamovil-virginia?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - STORAGE_PATH=/app/data/
      - LOG_PATH=/app/logs/
    restart: on-failure